// Writes Sources/Tandem/ZigTables.swift, the Float64 normal ziggurat tables, from the spec's
// table file (Appendix A, "Normals"):
//   swift tools/gen_zig_tables.swift ../tandem-spec/tables/normal_f64_zig1024.json
// Its SHA-256 must match the value the spec publishes, so a changed table file fails here
// instead of changing the normals. The hexadecimal floats are Swift literals, copied verbatim.
import CryptoKit
import Foundation

let sha256 = "8b961dd46a2582b953bd8780138edb0ad712e3d243a366a123ffc8978d0a33ab"
let layers = 1024

struct Tables: Decodable {
    let layers: Int
    let R: String
    let W: [String], K: [UInt64], Y: [String]
}

func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data((message + "\n").utf8))
    exit(1)
}

func hexfloat(_ s: String) -> String {
    guard s.wholeMatch(of: #/0x1\.[0-9a-f]{13}p[+-][0-9]+/#) != nil else { fail("not a canonical hexadecimal float: \(s)") }
    return s
}

func rows(_ values: [String]) -> String {
    stride(from: 0, to: values.count, by: 4).map { "    " + values[$0..<min($0 + 4, values.count)].joined(separator: ", ") + "," }
        .joined(separator: "\n")
}

guard CommandLine.arguments.count == 2 else { fail("usage: swift tools/gen_zig_tables.swift <normal_f64_zig1024.json>") }
let path = CommandLine.arguments[1]
guard let data = FileManager.default.contents(atPath: path) else { fail("cannot read \(path)") }
let digest = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
guard digest == sha256 else { fail("\(path): SHA-256 \(digest), expected \(sha256)") }
let t = try JSONDecoder().decode(Tables.self, from: data)
guard t.layers == layers && t.W.count == layers && t.K.count == layers && t.Y.count == layers + 1 else {
    fail("unexpected table sizes")
}
let w = t.W.map(hexfloat)

let source = """
    // Generated by tools/gen_zig_tables.swift from the spec's tables/normal_f64_zig1024.json
    // (SHA-256 \(sha256)). Do not edit.
    //
    // The Float64 normal ziggurat of Appendix A with \(layers) layers. zigW holds the widths W[i] for a
    // clear sign bit and -W[i] at \(layers) + i for a set one, so the table index is the low 11 bits of
    // a draw.

    let zigR = \(hexfloat(t.R))

    let zigW: [Double] = [
    \(rows(w + w.map { "-" + $0 }))
    ]

    let zigK: [UInt64] = [
    \(rows(t.K.map(String.init)))
    ]

    let zigY: [Double] = [
    \(rows(t.Y.map(hexfloat)))
    ]

    """
FileManager.default.createFile(
    atPath: URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("../Sources/Tandem/ZigTables.swift").path,
    contents: Data(source.utf8))
